#############################################################################
# Makefile for building: Bonsaicare
# Generated by qmake (2.01a) (Qt 4.7.4) on: ven 10. feb 18:18:39 2012
# Project:  Bonsaicare.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf Bonsaicare.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DVER="\"1.1\"" -DQ_COMPONENTS_SYMBIAN -DHAVE_MOBILITY -DQT_DECLARATIVE_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtSql"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtDeclarative"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/sys"  -I"C:/Users/Mattia/Workspace/bonsai-care/qmlapplicationviewer"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/stlportv5"  -I"C:/Users/Mattia/Workspace/bonsai-care/moc"  -I"C:/Users/Mattia/Workspace/bonsai-care"  -I"C:/Users/Mattia/Workspace/bonsai-care/rcc"  -I"C:/Users/Mattia/Workspace/bonsai-care/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/Users/Mattia/Workspace/bonsai-care/Bonsaicare.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Users/Mattia/Workspace/bonsai-care/Bonsaicare.pro
	$(QMAKE) "C:/Users/Mattia/Workspace/bonsai-care/Bonsaicare.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc: 
	$(QMAKE) "C:/Users/Mattia/Workspace/bonsai-care/Bonsaicare.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/release/winscw/udeb/Bonsaicare.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis Bonsaicare.sis Bonsaicare.exe $(QT_RUN_OPTIONS)

Bonsaicare_template.pkg: C:/Users/Mattia/Workspace/bonsai-care/Bonsaicare.pro
	$(MAKE) -f $(MAKEFILE) qmake

Bonsaicare_installer.pkg: C:/Users/Mattia/Workspace/bonsai-care/Bonsaicare.pro
	$(MAKE) -f $(MAKEFILE) qmake

Bonsaicare_stub.pkg: C:/Users/Mattia/Workspace/bonsai-care/Bonsaicare.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: Bonsaicare_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) Bonsaicare_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: Bonsaicare_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o Bonsaicare_template.pkg $(QT_SIS_TARGET)

Bonsaicare.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: Bonsaicare_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: Bonsaicare_installer.pkg
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) Bonsaicare_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: Bonsaicare_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: Bonsaicare_installer.pkg
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o Bonsaicare_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: Bonsaicare_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) Bonsaicare_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call Bonsaicare.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_qmlapplicationviewer.cpp moc\moc_DatabaseManager.cpp moc\moc_weekmodel.cpp moc\moc_daymodel.cpp moc\moc_speciemodel.cpp moc\moc_bonsaimodel.cpp moc\moc_bonsai.cpp moc\moc_specie.cpp moc\moc_monthmodel.cpp moc\moc_day.cpp moc\moc_bonsaiworker.cpp moc\moc_orientationfilter.cpp moc\moc_Orientation.cpp moc\moc_operationmodel.cpp moc\moc_operation.cpp moc\moc_slot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_qmlapplicationviewer.cpp moc\moc_DatabaseManager.cpp moc\moc_weekmodel.cpp moc\moc_daymodel.cpp moc\moc_speciemodel.cpp moc\moc_bonsaimodel.cpp moc\moc_bonsai.cpp moc\moc_specie.cpp moc\moc_monthmodel.cpp moc\moc_day.cpp moc\moc_bonsaiworker.cpp moc\moc_orientationfilter.cpp moc\moc_Orientation.cpp moc\moc_operationmodel.cpp moc\moc_operation.cpp moc\moc_slot.cpp
moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\qmlapplicationviewer\qmlapplicationviewer.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_qmlapplicationviewer.cpp

moc\moc_DatabaseManager.cpp: DatabaseManager.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\DatabaseManager.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_DatabaseManager.cpp

moc\moc_weekmodel.cpp: daymodel.h \
		slot.h \
		operationmodel.h \
		operation.h \
		day.h \
		bonsaimodel.h \
		bonsai.h \
		speciemodel.h \
		specie.h \
		bonsaiworker.h \
		weekmodel.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\weekmodel.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_weekmodel.cpp

moc\moc_daymodel.cpp: slot.h \
		operationmodel.h \
		operation.h \
		day.h \
		bonsaimodel.h \
		bonsai.h \
		speciemodel.h \
		specie.h \
		bonsaiworker.h \
		daymodel.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\daymodel.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_daymodel.cpp

moc\moc_speciemodel.cpp: specie.h \
		speciemodel.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\speciemodel.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_speciemodel.cpp

moc\moc_bonsaimodel.cpp: bonsai.h \
		speciemodel.h \
		specie.h \
		bonsaiworker.h \
		bonsaimodel.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\bonsaimodel.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_bonsaimodel.cpp

moc\moc_bonsai.cpp: bonsai.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\bonsai.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_bonsai.cpp

moc\moc_specie.cpp: specie.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\specie.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_specie.cpp

moc\moc_monthmodel.cpp: monthmodel.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\monthmodel.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_monthmodel.cpp

moc\moc_day.cpp: day.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\day.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_day.cpp

moc\moc_bonsaiworker.cpp: bonsai.h \
		speciemodel.h \
		specie.h \
		bonsaiworker.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\bonsaiworker.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_bonsaiworker.cpp

moc\moc_orientationfilter.cpp: orientationfilter.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\orientationfilter.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_orientationfilter.cpp

moc\moc_Orientation.cpp: Orientation.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\Orientation.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_Orientation.cpp

moc\moc_operationmodel.cpp: operation.h \
		day.h \
		operationmodel.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\operationmodel.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_operationmodel.cpp

moc\moc_operation.cpp: operation.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\operation.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_operation.cpp

moc\moc_slot.cpp: operationmodel.h \
		operation.h \
		day.h \
		slot.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Mattia\Workspace\bonsai-care\slot.h -o c:\Users\Mattia\Workspace\bonsai-care\moc\moc_slot.cpp

compiler_rcc_make_all: rcc\qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc\qrc_resources.cpp
rcc\qrc_resources.cpp: resources.qrc \
		resources\db.xml
	c:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\rcc.exe -name resources c:\Users\Mattia\Workspace\bonsai-care\resources.qrc -o c:\Users\Mattia\Workspace\bonsai-care\rcc\qrc_resources.cpp

compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

dodistclean:
	-@ if EXIST "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_template.pkg" $(DEL_FILE)  "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_template.pkg"
	-@ if EXIST "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_stub.pkg" $(DEL_FILE)  "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_stub.pkg"
	-@ if EXIST "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_installer.pkg" $(DEL_FILE)  "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_installer.pkg"
	-@ if EXIST "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\distribution.policy.s60" $(DEL_FILE)  "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\distribution.policy.s60"
	-@ if EXIST "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_clean.flm" $(DEL_FILE)  "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_clean.flm"
	-@ if EXIST "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_emulator_deployment.flm" $(DEL_FILE)  "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_emulator_deployment.flm"
	-@ if EXIST "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_extra_pre_targetdep.flm" $(DEL_FILE)  "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_extra_pre_targetdep.flm"
	-@ if EXIST "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_post_link.flm" $(DEL_FILE)  "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_post_link.flm"
	-@ if EXIST "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_store_build.flm" $(DEL_FILE)  "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qmake_store_build.flm"
	-@ if EXIST "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qt.xml" $(DEL_FILE)  "c:\QtSDK\Symbian\SDKs\Symbian3Qt474\epoc32\tools\makefile_templates\qt\qt.xml"
	-@ if EXIST "c:\Users\Mattia\Workspace\bonsai-care\Makefile" $(DEL_FILE)  "c:\Users\Mattia\Workspace\bonsai-care\Makefile"
	-@ if EXIST "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_exe.mmp" $(DEL_FILE)  "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_exe.mmp"
	-@ if EXIST "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_reg.rss" $(DEL_FILE)  "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare_reg.rss"
	-@ if EXIST "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.rss" $(DEL_FILE)  "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.rss"
	-@ if EXIST "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc" $(DEL_FILE)  "c:\Users\Mattia\Workspace\bonsai-care\Bonsaicare.loc"
	-@ if EXIST "c:\Users\Mattia\Workspace\bonsai-care\bld.inf" $(DEL_FILE)  "c:\Users\Mattia\Workspace\bonsai-care\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


